-- A pluggable database was the one I used 
ALTER PLUGGABLE DATABASE ORCLPDB OPEN;

ALTER SESSION SET CONTAINER = ORCLPDB;

CREATE USER careconnect IDENTIFIED BY flavien;
GRANT CONNECT, RESOURCE TO careconnect;
ALTER USER careconnect QUOTA UNLIMITED ON USERS;

-- CARECONNECT – TABLE CREATION SCRIPT

CREATE TABLE patients (
    patient_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name      VARCHAR2(50) NOT NULL,
    last_name       VARCHAR2(50) NOT NULL,
    gender          VARCHAR2(10),
    dob             DATE NOT NULL,
    phone           VARCHAR2(20) UNIQUE,
    email           VARCHAR2(100),
    address         VARCHAR2(200)
);

CREATE TABLE doctors (
    doctor_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name      VARCHAR2(50) NOT NULL,
    last_name       VARCHAR2(50) NOT NULL,
    specialization  VARCHAR2(50),
    phone           VARCHAR2(20)
);

CREATE TABLE appointments (
    appointment_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id          NUMBER NOT NULL,
    doctor_id           NUMBER NOT NULL,
    appointment_date    DATE NOT NULL,
    appointment_time    VARCHAR2(10) NOT NULL,
    status              VARCHAR2(20),

    CONSTRAINT fk_app_patient FOREIGN KEY (patient_id)
        REFERENCES patients(patient_id),

    CONSTRAINT fk_app_doctor FOREIGN KEY (doctor_id)
        REFERENCES doctors(doctor_id)
);

CREATE TABLE treatments (
    treatment_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id   NUMBER NOT NULL,
    doctor_id        NUMBER NOT NULL,
    description      VARCHAR2(200),
    prescription     VARCHAR2(200),
    treatment_date   DATE NOT NULL,

    CONSTRAINT fk_treat_app FOREIGN KEY (appointment_id)
        REFERENCES appointments(appointment_id),

    CONSTRAINT fk_treat_doc FOREIGN KEY (doctor_id)
        REFERENCES doctors(doctor_id)
);

CREATE TABLE billing (
    bill_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    treatment_id   NUMBER NOT NULL,
    amount         NUMBER(10,2),
    status         VARCHAR2(20),
    payment_date   DATE,

    CONSTRAINT fk_bill_treat FOREIGN KEY (treatment_id)
        REFERENCES treatments(treatment_id)
);

CREATE TABLE feedback (
    feedback_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id      NUMBER NOT NULL,
    doctor_id       NUMBER NOT NULL,
    rating          NUMBER CHECK (rating BETWEEN 1 AND 5),
    comments        VARCHAR2(300),
    feedback_date   DATE NOT NULL,

    CONSTRAINT fk_fb_patient FOREIGN KEY (patient_id)
        REFERENCES patients(patient_id),

    CONSTRAINT fk_fb_doctor FOREIGN KEY (doctor_id)
        REFERENCES doctors(doctor_id)
);

CREATE TABLE audit_log (
    audit_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name   VARCHAR2(50),
    operation    VARCHAR2(20),
    record_id    NUMBER,
    old_value    CLOB,
    new_value    CLOB,
    changed_at   DATE DEFAULT SYSDATE
    attempt_by VARCHAR2(50),
    attempt_date DATE,
    status VARCHAR2(20),
    reason VARCHAR2(200)
);

CREATE TABLE holidays (
    holiday_date DATE PRIMARY KEY,
    description VARCHAR2(100)
);
